config/routes.rb
Rails.application.routes.draw do
  get 'estaticas/contacto'
  get 'estaticas/nosotros'
	
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def contacto
  	@mensaje = "Hola desde el controller"
  	@usuarios = ['Pablo','María','Silvia', 'Daniel']
  end

  def nosotros
  	
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/estaticas/contacto.html.erb
<% provide(:titulo,'Contacto') %> 
<h1>Estaticas#contacto</h1>
<p>Find me in app/views/estaticas/contacto.html.erb</p>
<%= @mensaje %>
<br>
<%= "El controller dice: #{@mensaje}" %>

<ul>
<% @usuarios.each do |i| %>
<%= "<li> #{i} </li>".html_safe %>
<% end %>	
</ul>

<%= link_to "Home", root_path %>
<%= link_to "Nosotros", estaticas_nosotros_path %>
<%= link_to "Contacto", estaticas_contacto_path %>

app/views/estaticas/nosotros.html.erb
<% provide(:titulo,'Nosotros') %>
<h1>Estaticas#nosotros</h1>
<p>Find me in app/views/estaticas/nosotros.html.erb</p>

app/views/home/index.html.erb
<% provide(:titulo,'Mi Blog') %>
<h1>HOLA</h1>
<p>Bienvenidos a mi blog</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:titulo) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Nosotros", estaticas_nosotros_path %>
<%= link_to "Contacto", estaticas_contacto_path %>